version: "3.8"
services:
  app:
    build: .
#    image: zahradkar/slon:socialnet_1.00
    container_name: app
    restart: always
    environment:
      - DB_URL=jdbc:mysql://db:3306/socialnet?createDatabaseIfNotExist=true
      - DB_USERNAME=root
      - DB_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.1
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_volume:/var/lib/mysql
#    networks:
#      - db_network
#
volumes:
  db_volume:
#networks:
#  db_network: